version: "3.9"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
